# Node.js 2

# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger: 
  none

pool: Default

stages:
- stage:  Install_and_Build #The Stage do you prefer
  #condition: eq(variables['Build.SourceBranch'], 'refs/heads/Testing') #If the change is from development branch the following job will be executed 
  pool: Default
  jobs: 
    - job: Install
      steps:
        - task: NodeTool@0
          inputs:
            versionSpec: '16.x'
          displayName: 'Install Node.js'
        - script: |
            rm -rf node_modules/
            npm install
            npm run build
          displayName: 'npm install and build'

- stage:  Deploy #The Stage do you prefer
  #condition: eq(variables['Build.SourceBranch'], 'refs/heads/Testing') #If the change is from development branch the following job will be executed 
  pool: Default
  jobs: #Chose the prefer job
    - job: Deploy_in_Firebase
      steps:
        - task: NodeTool@0
          inputs:
            versionSpec: '16.x'
          
        - task: CmdLine@2
          inputs:
            script: |
              npm install -g firebase-tools
          displayName: 'firebase install'
          
        - task: CmdLine@2
          inputs:
            script: | 
              cd..
              firebase deploy --token $(TOKEN)
          displayName: 'firebase deploy'
        
          
            




